schema: 1
organizationId: 00000000-0000-0000-0000-000000000000
packs:
  - schema: 2
    name: '@taskless/core'
    version: 1.0.0
    description: >
      Taskless core Telemetry. The core telemetry contains common monitoring and
      logging found in APM-like solutions, and is a solid baseline for any
      observability stack.
    permissions:
      domains:
        - .+
      capture:
        durationMs:
          type: number
          description: The duration of the request in milliseconds
        status:
          type: number
          description: The status code of the request
        domain:
          type: string
          description: The domain of the request
        url:
          type: string
          description: The full URL of the request
        path:
          type: string
          description: The path of the request in the form of '/path/to/resource'
    hooks:
      pre: |
        capture("domain", request.domain)
        capture("url", request.url)
        capture("path", request.path)
        context.set("start", now())
      post: |
        capture("durationMs", now() - context.get("start"))
        capture("status", response.status)
  - schema: 2
    name: '@taskless/observe'
    version: 1.0.0
    description: |
      Taskless observability
    permissions:
      domains:
        - .+
      response:
        - body
      capture:
        error:
          type: string
          description: >-
            In the event of errors, this contains the error message from common
            expected payload locations
    hooks:
      post: |
        local code = response.status
        local msg = get(response.body, "error") or
                    get(response.body, "message") or
                    get(response.body, "err", "type") or
                    nil

        if code >= 400 and msg then
          capture("error", msg)
        end
