schema: 1
organizationId: 00000000-0000-0000-0000-000000000000
packs:
  - schema: 2
    name: '@taskless/core'
    version: 1.0.0
    description: >
      Taskless core Telemetry. The core telemetry contains common monitoring and
      logging found in APM-like solutions, and is a solid baseline for any
      observability stack.
    permissions:
      domains: null
      capture:
        durationMs:
          type: number
          description: The duration of the request in milliseconds
        status:
          type: number
          description: The status code of the request
        domain:
          type: string
          description: The domain of the request
        url:
          type: string
          description: The full URL of the request
        path:
          type: string
          description: The path of the request in the form of '/path/to/resource'
    hooks:
      pre: |
        context.set("domain", request.domain)
        context.set("url", request.url)
        context.set("path", request.path)
        context.set("start", now())
      post: |
        taskless.capture("durationMs", now() - context.get("start"))
        taskless.capture("status", response.getStatus())
