/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A pack definition to be submitted to the Taskless cloud or loaded inline into the Taskless loader
 */
export interface Manifest {
  /**
   * The pack schema version used
   */
  schema: "pre1";
  /**
   * The pack name
   */
  name: string;
  /**
   * The pack version
   */
  version: string;
  /**
   * The pack description
   */
  description: string;
  /**
   * Describes the data this pack intends to capture
   */
  capture: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^(.*)$".
     */
    [k: string]: {
      /**
       * The type of data to capture
       */
      type: "string" | "number";
      description: string;
      [k: string]: unknown;
    };
  };
  /**
   * The permissions requested for this pack
   */
  permissions: {
    /**
     * The domains this pack is allowed to request data from as regular expressions.
     */
    domains?: string[];
    /**
     * The environment variables this pack is allowed to access on the host system
     */
    environment?: string[];
    /**
     * During the lifecycle, request access to additional properties such as 'headers' and 'body'
     */
    request?: string[];
    /**
     * During the lifecycle, response access to additional properties such as 'headers' and 'body'
     */
    response?: string[];
    [k: string]: unknown;
  };
  displays?: {
    /**
     * A name for the display module, unique to the pack
     */
    name: string;
    /**
     * The title
     */
    title: string;
    /**
     * Describes the query that retrieves data for this module
     */
    query: {
      count?: string;
      group?: string;
      where?: {
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^(.*)$".
         */
        [k: string]: string | number;
      };
      [k: string]: unknown;
    };
    /**
     * The default display mode for this module
     */
    display: "graph" | "table";
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
