/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Manifests describe packs as they're uploaded to Taskless. They contain additional metadata about the default displays, graphs, and configuration panels
 */
export interface Manifest {
  /**
   * The pack schema version used
   */
  schema: "pre2";
  /**
   * The pack name
   */
  name: string;
  /**
   * The pack version, using semantic versioning conventions
   */
  version: string;
  /**
   * A short description of the pack's functionality
   */
  description: string;
  /**
   * The permissions requested for this pack from the host system
   */
  permissions: {
    /**
     * The environment variables this pack is allowed to access on the host system
     */
    environment?: string[];
    /**
     * Whether this pack can access the request and response body
     */
    body?: boolean;
  };
  /**
   * Default dashboard configurations for this pack
   */
  displays?: {
    /**
     * A name for the display module, unique to the pack
     */
    name: string;
    /**
     * The title
     */
    title: string;
    /**
     * Describes the query that retrieves data for this module
     */
    query: {
      count?: string;
      group?: string;
      where?: {
        [k: string]: string | number;
      };
    };
    /**
     * The default display mode for this module
     */
    display: "graph" | "table";
  }[];
  /**
   * User-configurable fields for this pack
   */
  fields?: (
    | {
        name: string;
        type: "string";
        description: string;
        default: string;
      }
    | {
        name: string;
        type: "string[]";
        description: string;
        default: string[];
      }
    | {
        name: string;
        type: "number";
        description: string;
        default: number;
      }
    | {
        name: string;
        type: "number[]";
        description: string;
        default: number[];
      }
    | {
        name: string;
        type: "boolean";
        description: string;
        default: boolean;
      }
  )[];
}
